/**
 * 3D character model definitions for Higgsfield-generated assets.
 * Maps character keys to GLTF model URLs and voice bark configurations.
 */

export interface CharacterModelDef {
  key: string;
  modelUrl: string;
  voiceLines: Record<string, string>; // line key → audio URL
}

/**
 * Zip-In: Ice speedster with 3D model and voice barks.
 * Generated by Higgsfield.
 */
export const ZIP_IN_MODEL: CharacterModelDef = {
  key: 'zip',
  modelUrl: 'models/character-zip-in.glb',
  voiceLines: {
    spawn: 'voices/zip-in-spawn.wav',
    ability_charged: 'voices/zip-in-ability-charged.wav',
    hit: 'voices/zip-in-hit.wav',
    victory: 'voices/zip-in-victory.wav',
    taunt: 'voices/zip-in-taunt.wav',
    revival: 'voices/zip-in-revival.wav',
    ability_use: 'voices/zip-in-ability-use.wav',
    round_win: 'voices/zip-in-round-win.wav',
    surprise: 'voices/zip-in-surprise.wav',
    climax: 'voices/zip-in-climax.wav',
  },
};

/**
 * Registry of all 3D character models.
 * Falls back to 2D puppet animation if model is missing.
 */
export const CHARACTER_MODELS: Record<string, CharacterModelDef | undefined> = {
  zip: ZIP_IN_MODEL,
};

export function getCharacterModel(key: string): CharacterModelDef | undefined {
  return CHARACTER_MODELS[key];
}
